sudo: required
# language: generic

services:
  - docker

before_install:
  - docker build -t prakash/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true prakash/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-174253625304"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"