sudo: required
# language: generic

services:
  - docker

before_install:
  - docker build -t prakash/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true prakash/docker-react npm run test -- --coverage